### ISSUE TITLE
Problem with Naviation page on IOS Devices

### ISSUE THREAD

**Issue by hofi199410** [harshitgindra/Xamarin.AdmobExample#1]
Hello,

First of all, thank you very much for the excellent example, how to use AdMob in xamarin forms. 

Now to my issue, everything works well until I am using navigation page.

Bug reproduce steps:

1) Create Mainpage with an Admob Banner

2) Define Mainpage as a navigation page

3) Add a Button on MainPage, which navigates the user to Page1 with Navigation.PushAsync...

4) If you are at Page1, click the software back button and the program will crash with a NullReferenceException

On Android everything works well, maybe you can help me what is wrong in IOS?

**Comment by harshitgindra** [comment]
Hello,
Thanks for pointing that out. This issue has been fixed. I've checked in the fix. Please try that out.
